#pragma once
/* This file will be generated by the build process automatically
   You can modify this file to have sane values for local developer builds */

#define APP_VERSION "5.9.2"
#define APP_VERSION_STRING "5.9.2 Build 10042"
#define APP_VERSION_NUM 0x00005092
#define BUILD_NUMBER 10042
#define WINLAMP_FILEVER 5,9,2,10042
#define WINLAMP_PRODUCTVER 5,9,2,10042
#define STR_WINLAMP_FILEVER "5,9,2,10042"
#define STR_WINLAMP_PRODUCTVER "5,9,2,10042"
#define SPECIAL_BUILD_NAME L"WinLAMP"
